export { default as getPathsData } from "./get-paths-data.js";
export { default as getGlobalData } from "./get-global-data.js";
export { default as getArticleData } from "./get-article-data.js";
export { default as getHomePageData } from "./get-home-page-data.js";
export { default as getRelatedArticlesData } from "./get-related-articles-data.js";
export { default as getAuthorData } from "./get-author-data.js";
export { default as getListedArticlesData } from "./get-listed-articles-data.js";
export { default as getCategoryData } from "./get-category-data.js";
export { default as getTagData } from "./get-tag-data.js";
